honeypotio/blog-honeypot-io

_includes/head.html
_layouts/default.html
_sass/_cookie-law.scss
_sass/app/settings/_variables.scss
css/jquery.cookiebar.css
css/main.scss
scripts/cookie_policy.js
scripts/jquery.cookiebar.js

https://www.pivotaltracker.com/story/show/115918551

Show notice about the cookie policy to the new users [#115918551]

---

_posts/2016-08-22-ask-a-cto-michael-kugele-from-nu3.md

This reverts commit aca6d62601056886696b108bd41b513ac369786c.

adds cto interview blog post

---

_posts/2016-08-23-fullstack-developer.md

- Corrects the origins of fullstack to 90s.

Entry paragraph edit

---

_posts/2016-09-01-whats-it-like-to-work-at-tomtom.md

- Tomtom post has a broken image link

Fixing tomtom image link

---

_posts/2016-09-01-what-is-devops.md

- Turns out it's another branch that needs merging

Reinstating devops post to 09/09

---

_posts/2016-03-09-berlin-startups.md
_posts/2016-03-15-what-documents-are-needed-for-eu-work-visa.md
_posts/2016-04-25-berlin-scala-community.md
_posts/2016-05-13-honeypot-tech-meetup-graphql.md
_posts/2016-05-28-hamburg-startup-map.md

[#132735469](https://www.pivotaltracker.com/story/show/132735469)

Rename "how does it work" to "how it works"

---

_config.yml

- update GitHub username
- add exclude files
- reorder sections + describe

chore(jekyll): config update

---

index.html

feature: add pagination fa icons

---

_sass/app/components/_footer.scss

fix(css): remove horizontal scrollbar on small viewports

---

_includes/sign-up.html
_layouts/post.html
_sass/app/application.scss
_sass/app/components/_author-info.scss
_sass/app/components/_sign-up.scss
_sass/app/settings/_variables.scss

- Try signing up through the form at the bottom of the page
- It should autofill the signup form on the sign-up page 
Keep in mind: It might not auto-fill the first name if this is not pushed to production: https://github.com/honeypotio/honeypot/pull/547

Sign up through a conversion box below a blog article [#132900271]

---

_includes/sidebar-signup.html
_layouts/post.html
_sass/app/application.scss
_sass/app/components/_featured-posts.scss
_sass/app/components/_sidebar-signup.scss
scripts/app.js

- Make sure the sidebar sticks to the side when scrolling

Signup box next to article [#132900819]

---

_includes/header.html

https://github.com/honeypotio/honeypot/issues/594

Rename 'Sign in' to 'Login' for non-logged-in users #594

---

_includes/header.html
_sass/app/framework/_overrides.scss
_sass/app/framework/overrides/_buttons.scss
_sass/app/framework/overrides/_navbar.scss
_sass/app/framework/overrides/_navs.scss

__before:__
__after:__
honeypotio/honeypot#595

feat: add "Sign up" CTA button to nav

---

_includes/footer.html

Use Liquid markup to get the current year for copyright.

Happy new year 🎆

---

_includes/header.html

[honeypot#639](https://github.com/honeypotio/honeypot/pull/639)

Rename /sign_in to /login

---

_includes/footer.html

Autotech link to the footer

---

scripts/app.js

Sticky sidebar for blog breaks on browser window resize [#1117]

---

_includes/latest-posts.html
_layouts/post.html
_sass/app/application.scss
_sass/app/components/_latest-posts.scss

Adds "You might also like" posts. (Latest posts of the same cateory)
https://staging-blog-honeypot-pr-122.herokuapp.com/
https://github.com/honeypotio/honeypot/issues/981

Latest similar post suggestions

---

_includes/head.html

When sharing a blog article on social sites, I can see a preview image. [#1143]

---

_posts/2017-04-11-3d-hub-amsterdam.md

@emmalou this is the initial post. I omitted one question but you can look into it and see whether it's worth including it.

3D hubs initial post

---

_includes/header.html
_sass/app/framework/overrides/_navbar.scss

Make the navigation consistent throughout the app [#1285]

---

_posts/2017-05-12-london-tech-map-2017.md

London Tech map

---

_posts/2017-08-31-30%-tax-ruling-in-the-netherlands.md

Hi Emma, I made a few corrections to the post!

corrections to original tax blog

---

_includes/header.html

https://github.com/honeypotio/honeypot/issues/2108

Xmas logo [#2108]

---

_includes/header.html

Remove Santabear logo [#2141]

---

_posts/2018-02-09-how-to-make-a-honeypot-profile-in-seven-easy-steps.md

updated video embed link for this blog post (seven steps)

fixed video

---

_posts/2018-04-26-tech-salaries-2018-amsterdam.md

This probably worked fine but best to be sure!

Add space between anchor attributes

---

_posts/2017-10-23-greenhouse.md

https://github.com/honeypotio/honeypot/issues/3092

Greenhouse formatting

---

_includes/header.html

Fixes https://github.com/honeypotio/honeypot/issues/2191

Fix login link on blog

---

_config.yml
_data/post_cta.yml
_includes/post-cta.html
_includes/sign-up.html
_layouts/post.html
_posts/2019-01-17-7-recruitment-tips.md

https://github.com/honeypotio/honeypot/issues/3755

Fix CTA attributes so that form prefills properly

---

_posts/2016-05-28-hamburg-startup-map.md
_posts/2016-10-17-if-hemingway-wrote-javascript.md
_posts/2017-04-11-3d-hub-amsterdam.md
_posts/2018-04-18-tech-salaries-2018-germany.md
_posts/2019-02-07-ultimate-guide-eu-blue-card.md
_posts/2019-05-03-amsterdam-salaries.md

just optimised a bunch of articles.

SEOchanges0120

---

_posts/2020-04-14-hiring-freeze.md

hyperlink edit

---

_includes/footer.html
_includes/head.html
_layouts/cookie-declaration.html
_layouts/default.html
bower.json
browse/cookie-declaration/index.html
scripts/app.js

Add Cookiebot to manage cookie consent.
related issue:
https://github.com/honeypotio/home/issues/726

Add cookiebot

---

_includes/head.html

Add script tag to load UTM stashing script.
For now we are using production as source, but in the future we should add staging as well.
https://github.com/honeypotio/home/issues/731 and https://github.com/honeypotio/home/issues/740 for more.

Add script tag to load UTM stashing script

---

_sass/_cookie-law.scss

Replacing the old styles with the new ones for the Cookiebot banner implementation.
@izabellima and I found this bug during bug triage :)

Replacing the old cookiebanner styles

---

_includes/footer.html

Issue regarding link on the blog repository: https://app.clickup.com/t/m9buxa

Fix url link to privacy policy page

---

_includes/footer.html
_includes/header.html

Remove the no longer live "research" and "autotech" page links

feat: remove research link

---

_posts/2017-12-05-how-to-integrate-personio-and-honeypot.md

Only push once images are available

Updates to Personio article

---

_posts/2017-10-23-greenhouse.md

numbering-fix-2-bullets

---

_posts/2016-05-28-hamburg-startup-map.md

Someone in Honeypot received the following message. This fixes the URL for the company that reported it

fix: roccat fixed url

---

_posts/austria-work-visa-blog.md

article about austria work visas

austria-work-visa-post.md

---

_includes/header.html
_posts/2015-11-09-8-steps-to-get-a-job-and-a-visa-in-Germany.md
_posts/2015-11-18-EU-blue-card-for-software-developers.md

[HONEY-2768](https://app.clickup.com/t/2595392/HONEY-2768)
This fixes the broken links direction to the the platform's `Signup` and `Login` pages

fix(App): fix singup and login links for honeypot app

---

README.md
_posts/2017-12-05-how-to-integrate-personio-and-honeypot.md

Update the personio guide on the blog
https://app.clickup.com/t/2595392/HONEY-3232

Update Personio Guide

---

_posts/2017-12-05-how-to-integrate-personio-and-honeypot.md

Minor fixes that I missed in the first attempt: https://github.com/honeypotio/blog-honeypot-io/pull/430
1. missing space
2. missing title

Honey 3232/update personio guide

---

_posts/2017-12-05-how-to-integrate-personio-and-honeypot.md

Need to move the picture under the section is should be from

fix(move picture to be with the section it belongs to)

---

_data/post_cta.yml
_includes/sidebar-signup.html

updating 1) sidebar cta and 2) variable (recruiter version) cta at bottom on blog

b2b updates to blog text

---

_posts/2019-05-13-lydia-hallie-interview.md

I forgot to delete one photo in the article. Now it's deleted

remote-photos-lydia-article-fix

---

_config.yml

Updating meta tags (title and description) as requested by @hannah-honeypot 
However, I only updated the meta tags in English because 
1) I have no clue whatsoever how to configure different languages for the meta tags 😅 
2) the blog is only in English anyway, so I guess it doesn't matter much 🙏 
ps: I didn't see a way to provide meta tags other than title and description (which wasn't the case now but maybe something we'll want to do at some point?); however we'll be working on migrating the blog to Contentful soon, which will allow us (and more importantly **you**) to manage such things more easily

Update meta tags

---

_includes/footer.html

Updating blog copy to New Work SE

chore: update copy right to New Work SE
